// <auto-generated />
using System;
using InstantMapUpdateProject.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InstantMapUpdateProject.API.Migrations
{
    [DbContext(typeof(UpdateMapContext))]
    partial class UpdateMapContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InstantMapUpdateProject.API.Models.Courier", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CourierId")
                        .HasColumnType("int");

                    b.Property<long?>("IdentityNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("identityNumber");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Courier");
                });

            modelBuilder.Entity("InstantMapUpdateProject.API.Models.OrderFollowCoordinate", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CourierId")
                        .HasColumnType("int");

                    b.Property<string>("RoomId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("centerLatitude")
                        .HasColumnType("DECIMAL(9,6)");

                    b.Property<decimal?>("centerLongitude")
                        .HasColumnType("DECIMAL(9,6)");

                    b.Property<decimal?>("courierLatitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("courierLongitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("userLatitude")
                        .HasColumnType("DECIMAL(9,6)");

                    b.Property<decimal?>("userLongitude")
                        .HasColumnType("DECIMAL(9,6)");

                    b.HasKey("Id");

                    b.ToTable("OrderFollowCoordinates");
                });

            modelBuilder.Entity("InstantMapUpdateProject.API.Models.OrderFollowRoom", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("OrderNo")
                        .HasColumnType("bigint");

                    b.Property<long?>("PatientId")
                        .HasColumnType("bigint");

                    b.Property<string>("RoomId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("roomId");

                    b.HasKey("Id");

                    b.ToTable("OrderFollowRoom");
                });
#pragma warning restore 612, 618
        }
    }
}
